# Generated by Django 5.0.5 on 2024-05-30 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_cache',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_cache_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
