# Generated by Django 5.0.5 on 2024-06-05 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teg'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tegs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teg'),
        ),
    ]
