# Generated by Django 5.0.5 on 2024-06-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_question_teg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to='main.teg'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tegs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tegs_set', to='main.teg'),
        ),
    ]
