# Generated by Django 5.0.5 on 2024-06-15 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_subscription_alter_question_tegs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_subscr_set', to='main.teg')),
                ('user', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscr_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tag', 'user')},
            },
        ),
    ]
