# Generated by Django 5.0.5 on 2024-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subscription_subscr_cache_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscr_cache_updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
