# Generated by Django 5.0.5 on 2024-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_subscription_subscr_cache_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tag_dict',
            field=models.JSONField(default=dict),
        ),
    ]
