# Generated by Django 5.0.5 on 2024-06-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_subscription_tag_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tag_dict',
            field=models.JSONField(),
        ),
    ]
