# Generated by Django 5.0.5 on 2024-06-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_subscription_tag_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='tag_dict',
        ),
    ]
