# Generated by Django 5.0.5 on 2024-07-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
