# Generated by Django 5.0.5 on 2024-07-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('notification_type', 'related_object_id', 'sender')},
        ),
    ]
